#!/usr/bin/env sh

echo "📝 Formatting staged files..."

FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E '\.(ts|js|json|yml|yaml)$')

if [ -n "$FILES" ]; then
  npx prettier --write $FILES
fi

echo "✅ Formatting complete!"
